#!/bin/sh
### BEGIN INIT INFO
# Provides:          rpiston
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rPiston web server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

DAEMON_NAME=rpiston
DAEMON=/usr/local/bin/rpiston/rpiston
DAEMON_ARGS=
DAEMON_USER=pi
PIDFILE=/tmp/rpiston_pidfile
LOGFILE=/tmp/rpiston.log

. /lib/lsb/init-functions

do_start () {
	log_daemon_msg "Starting system $DAEMON_NAME daemon"
	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas /bin/bash -- -c "exec $DAEMON $DAEMON_ARGS > $LOGFILE 2>&1"
	log_end_msg $?
}

do_stop () {
	log_daemon_msg "Stopping system $DAEMON_NAME daemon"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 10 
	log_end_msg $?
}

case "$1" in
	start|stop)
		do_${1}		
		;;
	restart|reload|force-reload)
		do_stop
		do_start
		;;
	status)
		status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0
		;;
	*)
		echo "Usage: /etc/init.d/rpiston start|stop|restart|status"
		exit 1
		;;
esac
exit 0

